version: '3.12'
services:
  web:
    build: ./authorization_app  
    command: sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./authorization_app:/app  
    ports:
      - "8000:8000" 
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy 

  db:
    image: postgres:15  
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432" 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_app"]  
      interval: 10s 
      timeout: 5s   
      retries: 5    

volumes:
  postgres_data:  
